# Generated by Django 6.1.1 on 2026-10-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_Details_DB',
            fields=[
                ('customer_name', models.CharField(max_length=10)),
                ('vehicl_model', models.CharField(max_length=10)),
                ('vehicl_model_num', models.IntegerField()),
                ('phone_number_1', models.IntegerField()),
                ('phone_number_2', models.CharField(max_length=20)),
                ('fuel_type', models.TextField()),
                ('licence_num', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('alternate_num', models.IntegerField()),
            ],
        ),
    ]
